### ISSUE TITLE
elementMgr.js 在vue中的一些问题

### ISSUE THREAD

**Issue by luogeng2017** [xiazeyu/live2d-widget.js#36]
在Vue中使用先说目前发现的几个问题吧：
1.在 elementMgr.js 中导入 import htmlTemplate from './tmplate/innerHTML';会报找到不模块。
解决：在后面加上‘.html’import htmlTemplate from './tmplate/innerHTML.html';
2在npm i live2d-widget后，需要再手动安装一下live2d-widget的依赖
3里面会生成‘[object Object]’字样，如下图
![qq 20180605114122](https://user-images.githubusercontent.com/29565303/40954079-6a5f8a26-68b5-11e8-9d38-4cb4e622e2be.png)
![qq 20180605112738](https://user-images.githubusercontent.com/29565303/40953863-3ffebcc6-68b4-11e8-926b-e4e0668119e1.png)

**Comment by xiazeyu** [comment]
2 您需要npm i --save live2d-widget

**Comment by luogeng2017** [comment]
哦，我就是npm i --save live2d-widget。
![qq 20180611110324](https://user-images.githubusercontent.com/29565303/41210976-324d87da-6d67-11e8-81f2-a2b13452b3b3.png)
我是用的`vue-cli3.0.x`构建的项目，后来通过上图那样改了，就好了。应该是vue-cli对不写 '.html'没处理好。那个`[object Object]`是`newElem.innerHTML = htmlTemplate;`造成的

**Comment by xiazeyu** [comment]
@luogeng2017 https://github.com/xiazeyu/live2d-widget.js/commit/20298ade792f45b75e89bd65a7e899e2611341a6
这个问题我在dev分支可能有解决了.
在将来的4.0版本中可以通过直接导入umd模块而不需自行编译

.html的问题是由于我们的webpack配置文件里有自动加后缀的设置。

README的错误在dev分支也获得了修正。

**Comment by luogeng2017** [comment]
嗯，这个项目很不错了，支持！
那个shizuku的桌角怎么调都显示不全，不知道是不是我设置的问题。

**Comment by xiazeyu** [comment]
@luogeng可能是插件画布缩放的问题..也有可能是模型自己的设置的问题...
不过话说显示不全是指什么..我看你的截图挺全的啊

**Comment by luogeng2017** [comment]
应该是画布问题。貌似通过config改不了。
![qq 20180612153501](https://user-images.githubusercontent.com/29565303/41276260-4c61b610-6e56-11e8-974c-e08529df0a40.png)

**Comment by xiazeyu** [comment]
Same with https://github.com/xiazeyu/live2d-widget.js/issues/12
