### ISSUE TITLE
移动端的scale参数不起作用

### ISSUE THREAD

**Issue by oukohou** [xiazeyu/live2d-widget.js#40]
# Issue
参数配置如下：
```html
<script src="/assets/live2dw/lib/L2Dwidget.min.js"></script>
    <script>L2Dwidget.init({
        "pluginRootPath": "live2dw/",
        "pluginJsPath": "lib/",
        "pluginModelPath": "assets/",
        "tagMode": false,
        "debug": false,
        "model": {"jsonPath": "/assets/live2dw/assets/unitychan.model.json"},
        "display": {"position": "right", "width": 120, "height": 180},
        "mobile": {"show": true, "scale": 0.02},
        "log": false
    });</script>
```

在电脑端能够跟随model.width、model.height而改变大小，但移动端的大小始终如一，一个示意图如下：

![644697106](https://user-images.githubusercontent.com/16237619/49351607-36b13580-f6ef-11e8-8201-70494f697899.jpg)

请问是否是移动端的参数有什么黑科技？
还是我哪里设置的不对？  
我的博客网址：[https://www.oukohou.wang/](https://www.oukohou.wang/)
谢谢，致礼！

- [x] I have alreday read instructions in [CONTRIBUTING](CONTRIBUTING.md).
  我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [x] I have alreday read instructions in [README](../README.md).
  我已仔细阅读[README](../README.md)中的相关内容。

@xiazeyu @EYHN

**Comment by xiazeyu** [comment]
..为什么我觉得当时的版本没有支持手机端的缩放Orzzz.
https://cdn.jsdelivr.net/npm/live2d-widget@3.0.5/src/elementMgr.js

你可以试着找找再前面的版本..我记得有一个是支持手机端缩放的

**Comment by EYHN** [comment]
fixed in 5aeafe4

**Comment by oukohou** [comment]
> fixed in [5aeafe4](https://github.com/xiazeyu/live2d-widget.js/commit/5aeafe48e1712e7124f1dbb24500523f1c0e76a0)

well, tested using Hexo, but seems nothing changes?  
 config:   
```text
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw_unitychan/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: unitychan
  display:
    position: right
#    vOffset: 100px
    width: 150
    height: 300
    show: true
  mobile:
    show: true
    scale: 1## tested 1, 0.5, 0.01, all the same. 
``` 
Tested scale `1, 0.5, 0.01`, all the same like: 
![image](https://user-images.githubusercontent.com/30198850/55388944-2b023e00-552c-11e9-9ba3-c5f94e6adc8f.png)

If you need the codes, can be found on the Google Drive:[hexo_blog_demo](https://drive.google.com/file/d/1CYT7iyPnqVO5jfZrUpPLXSJsTmQr_KOT/view?usp=sharing)

**Comment by oukohou** [comment]
> The hexo plugin has been updated to 3.1.1 please check your version.

@EYHN 
Yes. Thanks.
After running `yarn add hexo-helper-live2d@3.1.1`, now it works.
