### ISSUE TITLE
不能更换模型

### ISSUE THREAD

**Issue by rs-v** [xiazeyu/live2d-widget.js#42]
截图 ![ddd.png](https://s2.ax1x.com/2019/01/23/kEiDmV.png)

- [x] 我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [x] 我已仔细阅读[README](../README.md)中的相关内容。

@EYHN @xiazeyu

**Comment by xiazeyu** [comment]
是否 `npm install --save live2d-widget-model-miku`过?

**Comment by rs-v** [comment]
是

**Comment by xiazeyu** [comment]
请更新到最新版本的`hexo-helper-live2d`, 然后打开
```yml
live2d:
  log: true
```
看看调试输出是什么

**Comment by EYHN** [comment]
请在 [hexo-helper-live2d issues](https://github.com/EYHN/hexo-helper-live2d/issues) 中报告此问题
