### ISSUE TITLE
这个错误是什么意思？

### ISSUE THREAD

**Issue by lxsunbin** [xiazeyu/live2d-widget.js#46]
L2Dwidget.0.min.js:2618 Live2D 2.1.00_1
L2Dwidget.0.min.js:2615 profile : Desktop
L2Dwidget.0.min.js:2615   [PROFILE_NAME] = Desktop
L2Dwidget.0.min.js:2615   [USE_ADJUST_TRANSLATION] = false
L2Dwidget.0.min.js:2615   [USE_CACHED_POLYGON_IMAGE] = false
L2Dwidget.0.min.js:2615   [EXPAND_W] = 2
**L2Dwidget.0.min.js:551 dump exception : _$gi _$C _$li , _$Q0 _$P0.
L2Dwidget.0.min.js:551 stack :: undefined**

最后面两行的错误

**Comment by xiazeyu** [comment]
emmm
能详细一点吗...我也没见过

**Comment by lxsunbin** [comment]
> 这个是官方的Live2D自己报的错
> 我也不知道什么意思...
> 能用就行

好的
