### ISSUE TITLE
i don't know what mean `Use online generator`

### ISSUE THREAD

**Issue by zMingGit** [xiazeyu/live2d-widget.js#5]
where are the online generator? sorry, i don't understand.  i need help.

**Comment by xiazeyu** [comment]
It is still work in progress.
See https://github.com/EYHN/hexo-helper-live2d/issues/6.

**Comment by xiazeyu** [comment]
Close because this issue is the same of https://github.com/EYHN/hexo-helper-live2d/issues/81
