### ISSUE TITLE
页面内多次渲染 配置/模型不更新

### ISSUE THREAD

**Issue by sockball** [xiazeyu/live2d-widget.js#50]
## 描述你的问题
页面内成功渲染(`init`)过一次模型后，更换配置后再次渲染不生效（不刷新页面）...

## 追查原因
发现配置`src/config/configMgr.js`做了[更改](https://github.com/xiazeyu/live2d-widget.js/commit/eb0d1db40bca28098a2f18bf831cd600aecab2d7) 不知此处的更改是何故

从`src/config/defaultsDeep.js`现有逻辑来看
```
var val = target[key];
// add the missing property, or allow a null property to be updated
if (val == null) {
    target[key] = value;
} else if (typeof val === 'object' && val !== null && typeof value === 'object' && value !== null) {
    defaultsDeep(val, value);
}
```
第一次渲染后`target`（`currConfig`）每一项都有值，再次渲染后`if else`并不会更新`target`的值，**也就是少考虑了`val`为`string`的情况?**

## 尝试解决
* 还原此处[更改](https://github.com/xiazeyu/live2d-widget.js/commit/eb0d1db40bca28098a2f18bf831cd600aecab2d7) 考虑到事出有因，似乎不可取

* 上述`if else`逻辑改为（直接一个`else`可能欠妥？不知道还有没有其他情况）
```
if (typeof val === 'object' && val !== null && typeof value === 'object' && value !== null) {
    defaultsDeep(val, value);
} else {
    target[key] = value;
}
```
且`src/config/configMgr.js`中28行
`defaultsDeep(currConfig, userConfig, defaultConfig);`
更改为
`  defaultsDeep(currConfig, defaultConfig, userConfig);`

## 环境信息(请务必填写下列信息)
- 设备: [PC]
- 操作系统: [MACOS]
- 浏览器 [Chrome 73]
- live2d-widget: [3.1.4]

- [x] 我已仔细阅读[CONTRIBUTING](CONTRIBUTING.md)中的相关内容。

- [x] 我已仔细阅读[README](../README.md)中的相关内容。

@EYHN

**Comment by EYHN** [comment]
非常感谢！很抱歉目前版本没有允许多次init的设计，如果需要多次init或者实例化多个live2dweight对象需要对整体代码进行重构，短期内没有这样的打算。

**Comment by sockball** [comment]
> 非常感谢您的支持！很抱歉目前版本没有允许多次init的设计，如果需要多次init或者实例化多个live2dweight对象需要对整体代码进行重构，短期内没有这样的打算。

是这样吗...我以为`elementMgr.js`这段就是为多次init准备的😅，那现阶段只能自己瞎弄了
```
...

function createElement() {

  let e = document.getElementById(config.name.div)
  if (e !== null) {
    document.body.removeChild(e);
  }

...
```

**Comment by xiazeyu** [comment]
重构到一半突然去准备高考的我突然来露了个头(´Д⊂ヽ

**Comment by sockball** [comment]
> 重构到一半突然去准备高考的我突然来露了个头(´Д⊂ヽ

都4月了还是好好准备高考吧 还是说已经胸有成竹了😊
