### ISSUE TITLE
有嘤嘤嘤的模型嘛？

### ISSUE THREAD

**Issue by XNNNN** [xiazeyu/live2d-widget.js#54]
**你的新功能与某一个问题有关吗?**
请简明清晰地描述你的问题, 例如: 我常常因为 [...] 而失望

**你的方案是**
请简明清晰地描述你的方案

**一些你考虑过的替代方案有**
请简明清晰地描述你的考虑过的替代方案或功能

**额外的信息**
请在此处描述其他的内容或者一些有关此功能的截图

**Comment by xiazeyu** [comment]
你加油
推荐你一个地方
Live2DViewer EX
