### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by sxyugao** [xiazeyu/live2d-widget.js#56]
详见 https://github.com/EYHN/hexo-helper-live2d/issues/149

@EYHN @xiazeyu

**Comment by sxyugao** [comment]
@EYHN 没新的 release 啊。。

**Comment by sxyugao** [comment]
@xiazeyu 大佬您的travis部署出锅了，没有build。。

**Comment by xiazeyu** [comment]
@sxyugao 明天康康

**Comment by sxyugao** [comment]
@xiazeyu 大佬您是不是忘了
